# Publish all joint states -----------------------------------
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
# Joint Trajectory Controllers -------------------------------
rarm_controller:
#  type: effort_controllers/JointTrajectoryController
#  type: velocity_controllers/JointTrajectoryController
  type: position_controllers/JointTrajectoryController
  joints:
    - SHOULDER
    - ARM
    - FOREARM
    - WRIST1
    - WRIST2
    - HAND
    - FINGER1
    - FINGER2
    - FINGER3
  gains:
    SHOULDER : {p: 2000.0, i: 0.0, d: 0.0}
    ARM      : {p: 2000.0, i: 0.0, d: 0.0}
    FOREARM  : {p: 2000.0, i: 0.0, d: 0.0}
    WRIST1   : {p: 2000.0, i: 0.0, d: 0.0}
    WRIST2   : {p: 2000.0, i: 0.0, d: 0.0}
    HAND     : {p: 2000.0, i: 0.0, d: 0.0}
    FINGER1  : {p: 100.0, i: 0.0, d: 0.0}
    FINGER2  : {p: 100.0, i: 0.0, d: 0.0}
    FINGER3  : {p: 100.0, i: 0.0, d: 0.0}
rleg_controller:
#  type: effort_controllers/JointTrajectoryController
#  type: velocity_controllers/JointTrajectoryController
  type: position_controllers/JointTrajectoryController
  joints:
    - FR_FLIPPER
    - BR_FLIPPER
  gains:
    FR_FLIPPER : {p: 8000.0, i: 0.0, d: 0.0}
    BR_FLIPPER : {p: 8000.0, i: 0.0, d: 0.0}
lleg_controller:
#  type: effort_controllers/JointTrajectoryController
#  type: velocity_controllers/JointTrajectoryController
  type: position_controllers/JointTrajectoryController
  joints:
    - FL_FLIPPER
    - BL_FLIPPER
  gains:
    FL_FLIPPER : {p: 8000.0, i: 0.0, d: 0.0}
    BL_FLIPPER : {p: 8000.0, i: 0.0, d: 0.0}

robot_interface_controllers: ['rarm', 'rleg', 'lleg' ]
